name: btech_frontend
description: "BTECH Plus Automation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  provider: ^6.1.1
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2
  carousel_slider: ^5.1.1
  url_launcher: ^6.2.0
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  webview_flutter: ^4.13.0
  image_picker: ^1.2.1
  http_parser: ^4.1.2
  fl_chart: ^0.68.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/kuccps_bg.png
    - assets/kra_bg.png
    - assets/helb_bg.png
    - assets/eta_bg.png
    - assets/mpesa_card_bg.png
